### ISSUE TITLE
Add User to Group

### ISSUE THREAD

**Issue by Dinferno-lol** [JamesPartsafas/ConcordiaCurriculumManager#160] opened 2023-11-05 19:28 UTC
As an admin, I want to add a user to a group.

[Story Points: 2]
[Priority: Medium]
[Risk: Medium]

Demo steps:
Given I'm logged in as an admin,
I can view the manage groups page,
then reach the add user page for a specific group,
and add a user that isn't already in that group.

**Comment by JamesPartsafas** [comment] 2023-11-05 23:16
This issue is a duplicate of #119

**Closed by JamesPartsafas** 2023-11-05 23:16 UTC
Labels: group/role, general, task

**Comment by Dinferno-lol** [comment] 2023-11-06 14:15
> This issue is a duplicate of #119

Since the issue you're referencing in question doesn't specify the add or remove user pages specifically I figured this would be required

**Comment by JamesPartsafas** [comment] 2023-11-06 17:41
> > This issue is a duplicate of #119
> 
> Since the issue you're referencing in question doesn't specify the add or remove user pages specifically I figured this would be required

I just added a line to it to reference adding users.

**Comment by Dinferno-lol** [comment] 2023-11-09 03:27
https://github.com/JamesPartsafas/ConcordiaCurriculumManager/assets/77465567/37b4d29b-9acb-494f-aad8-4b18225088d0
