### ISSUE TITLE
Receive email notifications for submitted dossier

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/ConcordiaCurriculumManager#14] opened 2023-09-17 18:15 UTC
As an initiator, I want to receive an email notification regarding the status of a submitted dossier, so I can keep track of the status of my requests.

[Story Points: 8]
[Priority: Low]
[Risk: Medium]

Tasks:
- [ ]  #404

Demo steps:
Given I’m an initiator 
When I submitted a dossier, and an approver makes an action on the dossier
Then an email notification is sent to me

**Comment by JamesPartsafas** [comment] 2024-02-09 15:02
This is a duplicate of #18

**Closed by JamesPartsafas** 2024-02-09 15:02 UTC
Labels: wontfix, story, notification
