### ISSUE TITLE
Create an add program dossier

### ISSUE THREAD

**Issue by zihao429** [JamesPartsafas/ConcordiaCurriculumManager#12] opened 2023-09-17 18:08 UTC
As an initiator, I want to create an add program dossier, so I can update the school’s curriculum to industry standards.

[Story Points: 8]
[Priority: High]
[Risk: Medium]

Tasks:

Demo steps:
Given I’m an initiator and I’m on the Add Program page
When I fill in the required fields, and click the Submit Changes Button
Then a confirmation message is displayed, and the system creates an add program dossier

**Comment by JamesPartsafas** [comment] 2023-10-01 23:30
Duplicate of #7

**Closed by JamesPartsafas** 2023-10-01 23:30 UTC
Labels: story, initiation
